# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12ierqOtaKpvplNGsjaskclkrRsdfkKZM
"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib

x=np.arange(0,5,0.2)
y=np.sin(x)
x1=np.arange(5,12,0.3)
y1=np.cos(x1)
fig,ax1=plt.subplots()
ax1.plot(x1,y1)
fig,ay = plt.subplots()
ay.plot(x,y)
plt.grid(color="red")
plt.show()

